### ISSUE TITLE
Archetypes are skipped in queries

### ISSUE THREAD

**Issue by LastTalon** [matter-ecs/matter#141]
## Description

Occasionally entities in certain archetypes are missed when querying or using `queryChanged`. This is already fixed in `v0.9.0-beta.0` but not in `v0.8`. Since `v0.9` will be breaking, it would be good to fix this change long term in `v0.8` as well, but will need to be fixed with a different solution.

## Steps to reproduce

TBD

## Expected behavior

All entities in all matching archetypes should be iterated.

**Comment by memorycode** [comment]
Added in #137
