### ISSUE TITLE
No Releases Exist

### ISSUE THREAD

**Issue by ATK422** [matter-ecs/matter#26]
Currently there are no public releases for any version of matter. 
The suggested fix would be to publish the latest version and/or setup a CD pipeline to make deployment easily when necessary. 
If this is fixed, these changes should be reflected in #25

**Comment by jackTabsCode** [comment]
A deployment pipeline is already set up. I'm not sure if it would be worth the effort to recreate all of the past repo's releases.

**Comment by LastTalon** [comment]
I think it's best for people to go to the repo those were originally released under if they want those releases since they aren't actually managed by this repo. That is why I didn't copy them over when I was doing initial migration at least.
