### ISSUE TITLE
Example game packages an incompatible plasma

### ISSUE THREAD

**Issue by LastTalon** [matter-ecs/matter#45]
## Description

It seems like recent changes to the plasma slider have packaged an incompatible plasma version that complains about missing `initial` fields on the slider widget.

See: https://discord.com/channels/385151591524597761/402843211707449354/1211850232036462652

**Comment by LastTalon** [comment]
We can't seem to replicate this issue. Closing for now.

**Comment by Ukendio** [comment]
We can't replicate this bug. The example game depends on the newest dependency of plasma at v0.4.3. It shouldnt be possible to have that bug since we do not index at line 37
