### ISSUE TITLE
Hybrid use of RenderStepped and Heartbeat in Systems

### ISSUE THREAD

**Issue by rotntake** [matter-ecs/matter#53]
I couldn't find an open discussion on Discord nor sites. I didn't know where to ask this but:

How do I use a hybrid of Heartbeat and RenderStepped? Because as stated in the Begin function of the Loop module. You can do a hybrid use of both events. So, how do I do it?

**Comment by Ukendio** [comment]
This has been answered here: https://devforum.roblox.com/t/all-about-entity-component-system/1664447/10?u=ukendio
