### ISSUE TITLE
Debugger table formatting has extra newlines at the top level

### ISSUE THREAD

**Issue by jackTabsCode** [matter-ecs/matter#70]
The issue is found in https://github.com/matter-ecs/matter/blob/main/lib/debugger/formatTable.lua

![image](https://github.com/matter-ecs/matter/assets/44332148/504c428e-603b-463f-9e5b-98066a5f0412)

**Comment by Ukendio** [comment]
Closed with #69

**Comment by Nidoxs** [comment]
Closed with #97.
