### ISSUE TITLE
FPS Unlocker breaks debugger 

### ISSUE THREAD

**Issue by ATK422** [matter-ecs/matter#9]
If you have something that ([FPS unlocks Studio](https://github.com/axstin/rbxfpsunlocker)), then the output gets duplicated, however it only stays for one frame.

![image](https://github.com/matter-ecs/matter/assets/54485972/101f0bf2-2add-422d-a0d5-18af31373b8e)

From my testing this isn't a issue with matter or plasma as this seems like a studio issue due to it working perfectly fine on the client.

**Comment by LastTalon** [comment]
This still seems like it's worth figuring out what a potential fix could be for users with these circumstances, but we'd need a lot more information on what causes it in particular.
